/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 *
 * Detailed information about configuring a multi-project build in Gradle can be found
 * in the user manual at https://docs.gradle.org/5.5.1/userguide/multi_project_builds.html
 */

rootProject.name = "sypet"

include(
    "sypet-api",
    "sypet-cli",
    "sypet-compiler-api",
    "sypet-gui",
    "sypet-intellij-plugin",
    "sypet-lang-api",
    "sypet-petrinet-backend",
    "sypet-petrinet-backend-api",
    "sypet-petrinet-frontend-api",
    "sypet-petrinet-middleware",
    "sypet-petrinet-middleware-api",
    "sypet-rest-api",
    "sypet-runtime-api",
    "sypet-sketcher-api",
    "sypet-sketch-solver-api",
    "reachability-lib"
)